### ISSUE TITLE
-m switch fails

### ISSUE THREAD

**Issue by 0xtf** [averagesecurityguy/exfil#1]
Hi,

On both server and client, when specifying the method, with -m, the following error is given:

```
./exfil.py -s IP -p 5353 -d "TEST" -m dns_lookup
usage: exfil.py [-h] [-d string | -f filename] (-l | -s server) [-p port]
                module_name
exfil.py: error: unrecognized arguments: -m
```

Details:

```
pip show dpkt
---
Name: dpkt
Version: 1.9.0
Location: /usr/local/lib/python2.7/dist-packages
```

```
pip show dnslib
---
Name: dnslib
Version: 0.9.7
Location: /usr/local/lib/python2.7/dist-packages
```

Since it works without the switch, but it's just a matter of removing it from the documentation?

Thank you!

**Comment by averagesecurityguy** [comment]
Fixed documentation: https://github.com/averagesecurityguy/exfil/commit/992e3f7d27ff6fb264ed99cac1fcdfd85a22f9aa
